### ISSUE TITLE
Add bigwig creation step

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#23]
It would be great if the pipeline also created a bigwig file as an output. 

- this should happen after 'merge_files' (https://github.com/NAL-i5K/NAL_RNA_seq_annotation_pipeline/blob/master/rnannot/RNAseq_annotate.py#L477)
- use https://github.com/NAL-i5K/bam_to_bigwig
- you can use this command: `bam_to_bigwig.py output.bam -s -q -d -u -o output.bigwig`

Also, it looks like bam_to_bigwig might need to be updated to python3, and the rsem dependency might give us problems. Let me know how it goes.

**Comment by mpoelchau** [comment]
We need to re-write bam_to_bigwig. 

1. Figure out samtools command to remove secondary alignments etc. (what -s -q -d -u  did for us formerly) (@suryasaha will help) 
2. Decide whether to use bedtools or rsem to convert to intermediate format. Bedtools is more portable. But we already had rsem figured out. Let's stick with rsem for now - modify command to not use 'ignore_secondary' etc. 
3. Run wig2bigwig as usual

@Kelly - up to you if you want to do this in python3 vs. in cwl.

**Comment by suryasaha** [comment]
@kelly - `samtools view -F 15` should apply the following filters on the bam file but please double check
- 0x100	SECONDARY	secondary alignment
- 0x200	QCFAIL	not passing quality controls
- 0x400	DUP	PCR or optical duplicate
- 0x800	SUPPLEMENTARY	supplementary alignment

The other way to filter BAM would be with [bamtools] and the filter command (https://github.com/pezmaster31/bamtools/wiki)
![image](https://user-images.githubusercontent.com/1084749/79588279-b00db600-80a1-11ea-9486-f07b010609e1.png)

**Comment by mpoelchau** [comment]
After our discussion today - the pipeline should generate 2 bigwig files:
- from the merged bam file, before downsampling
- from the downsampled bam file

**Comment by mpoelchau** [comment]
Actually, 1 bigwig file will be generated, because we're now normalizing the reads, and not the bam file.
