### ISSUE TITLE
Change default name prefix

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#24]
It would be great if the final output file names could be changed  to the format - 

- downsampled, sorted bam file: `[gggsss]_[assemblyname]_downsampled-RNA-Seq-alignments_[date].bam`
- downsampled, sorted bam index file: `[gggsss]_[assemblyname]_downsampled-RNA-Seq-alignments_[date].bam.bai`
- downsampled bigwig file: `[gggsss]_[assemblyname]_downsampled-RNA-Seq-alignments_[date].bigwig`
- not downsampled bigwig file: `[gggsss]_[assemblyname]_RNA-Seq-alignments_[date].bigwig`

**Comment by HsiuKangHuang** [comment]
I noticed that there are two output.bam files.
One is in the directory "rnannot/2020-04-09-22-52-00/" (the working directory) and the other one is in "rnannot/2020-04-09-22-52-00/SRR1793080" (the SRR folder under working directory)
Do we need to change the one inside SRR1793080 too? or just the one at "rnannot/2020-04-09-22-52-00/"?

**Comment by mpoelchau** [comment]
I'm not sure how the files differ. Which one is the 'final' output file?

**Comment by HsiuKangHuang** [comment]
I think the one in "rnannot/2020-04-09-22-52-00/" (the working directory) is the final one.
It is the combination of each SRR output.bam file.

**Comment by mpoelchau** [comment]
Okay! For now, let's focus on the one in the working directory. Thanks!

**Comment by HsiuKangHuang** [comment]
In the tsv file, we don't have the info of [assemblyname] but I found a couple of Edirect commands can get assembly name by tax_id. 
https://www.biostars.org/p/346408/

I am trying to add it into tsv file; therefore, the rna_seq_annotate.py can use it as a parameter.

**Comment by mpoelchau** [comment]
That's worth a try. The person running the pipeline might have to add it themselves, though, since an organism can have multiple genome assemblies.

**Comment by HsiuKangHuang** [comment]
This is what I got after running " elink -db taxonomy -id 1049336 -target assembly | esummary "

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DocumentSummarySet PUBLIC "-//NLM//DTD esummary assembly 20180216//EN" "https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20180216/esummary_assembly.dtd">
<DocumentSummarySet status="OK">
<DocumentSummary>
<Id>1489481</Id>
	<RsUid></RsUid>
	<GbUid>5777088</GbUid>
	<AssemblyAccession>GCA_000507165.2</AssemblyAccession>
	<LastMajorReleaseAccession>GCA_000507165.2</LastMajorReleaseAccession>
	<LatestAccession></LatestAccession>
	<ChainId>507165</ChainId>
	<AssemblyName>Edan_2.0</AssemblyName>
	<UCSCName></UCSCName>
	<EnsemblName></EnsemblName>
	<Taxid>1049336</Taxid>
	<Organism>Ephemera danica (mayflies)</Organism>
	<SpeciesTaxid>1049336</SpeciesTaxid>
	<SpeciesName>Ephemera danica</SpeciesName>
	<AssemblyType>haploid</AssemblyType>
	<AssemblyClass>haploid</AssemblyClass>
	<AssemblyStatus>Scaffold</AssemblyStatus>
	<WGS>AYNC02</WGS>
	<GB_BioProjects>
		<Bioproj>
			<BioprojectAccn>PRJNA171755</BioprojectAccn>
			<BioprojectId>171755</BioprojectId>
		</Bioproj>
	</GB_BioProjects>
	<GB_Projects>
	</GB_Projects>
	<RS_BioProjects>
	</RS_BioProjects>
	<RS_Projects>
	</RS_Projects>
	<BioSampleAccn>SAMN02264621</BioSampleAccn>
	<BioSampleId>2264621</BioSampleId>
	<Biosource>
		<InfraspeciesList>
		</InfraspeciesList>
		<Sex>male</Sex>
		<Isolate></Isolate>
	</Biosource>
	<Coverage>207.7</Coverage>
	<PartialGenomeRepresentation>false</PartialGenomeRepresentation>
	<Primary>5777028</Primary>
	<AssemblyDescription></AssemblyDescription>
	<ReleaseLevel>Major</ReleaseLevel>
	<ReleaseType>Major</ReleaseType>
	<AsmReleaseDate_GenBank>2017/12/13 00:00</AsmReleaseDate_GenBank>
	<AsmReleaseDate_RefSeq>1/01/01 00:00</AsmReleaseDate_RefSeq>
	<SeqReleaseDate>2017/12/12 00:00</SeqReleaseDate>
	<AsmUpdateDate>2017/12/13 00:00</AsmUpdateDate>
	<SubmissionDate>2017/12/12 00:00</SubmissionDate>
	<LastUpdateDate>2017/12/13 00:00</LastUpdateDate>
	<SubmitterOrganization>The i5k Initiative</SubmitterOrganization>
	<RefSeq_category>representative genome</RefSeq_category>
	<AnomalousList>
	</AnomalousList>
	<ExclFromRefSeq>
	</ExclFromRefSeq>
	<PropertyList>
		<string>full-genome-representation</string>
		<string>latest</string>
		<string>latest_genbank</string>
		<string>representative</string>
		<string>wgs</string>
	</PropertyList>
	<FromType></FromType>
	<Synonym>
		<Genbank>GCA_000507165.2</Genbank>
		<RefSeq></RefSeq>
		<Similarity></Similarity>
	</Synonym>
	<ContigN50>55305</ContigN50>
	<ScaffoldN50>599527</ScaffoldN50>
	<FtpPath_GenBank>ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/507/165/GCA_000507165.2_Edan_2.0</FtpPath_GenBank>
	<FtpPath_RefSeq></FtpPath_RefSeq>
	<FtpPath_Assembly_rpt>ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/507/165/GCA_000507165.2_Edan_2.0/GCA_000507165.2_Edan_2.0_assembly_report.txt</FtpPath_Assembly_rpt>
	<FtpPath_Stats_rpt>ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/507/165/GCA_000507165.2_Edan_2.0/GCA_000507165.2_Edan_2.0_assembly_stats.txt</FtpPath_Stats_rpt>
	<FtpPath_Regions_rpt></FtpPath_Regions_rpt>
	<SortOrder>2C5X9999446940005071659700</SortOrder>
	<Meta><Stats> <Stat category="alt_loci_count" sequence_tag="all">0</Stat> <Stat category="chromosome_count" sequence_tag="all">0</Stat> <Stat category="contig_count" sequence_tag="all">25743</Stat> <Stat category="contig_l50" sequence_tag="all">2233</Stat> <Stat category="contig_n50" sequence_tag="all">55305</Stat> <Stat category="non_chromosome_replicon_count" sequence_tag="all">0</Stat> <Stat category="replicon_count" sequence_tag="all">0</Stat> <Stat category="scaffold_count" sequence_tag="all">8161</Stat> <Stat category="scaffold_count" sequence_tag="placed">0</Stat> <Stat category="scaffold_count" sequence_tag="unlocalized">0</Stat> <Stat category="scaffold_count" sequence_tag="unplaced">8161</Stat> <Stat category="scaffold_l50" sequence_tag="all">216</Stat> <Stat category="scaffold_n50" sequence_tag="all">599527</Stat> <Stat category="total_length" sequence_tag="all">474347418</Stat> <Stat category="ungapped_length" sequence_tag="all">448234373</Stat> </Stats> <FtpSites>   <FtpPath type="Assembly_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/507/165/GCA_000507165.2_Edan_2.0/GCA_000507165.2_Edan_2.0_assembly_report.txt</FtpPath>   <FtpPath type="GenBank">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/507/165/GCA_000507165.2_Edan_2.0</FtpPath>   <FtpPath type="Stats_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/507/165/GCA_000507165.2_Edan_2.0/GCA_000507165.2_Edan_2.0_assembly_stats.txt</FtpPath> </FtpSites> <assembly-level>2</assembly-level> <assembly-status>Scaffold</assembly-status> <representative-status>representative genome</representative-status> <submitter-organization>The i5k Initiative</submitter-organization></Meta>
</DocumentSummary>
</DocumentSummarySet>

**Comment by HsiuKangHuang** [comment]
This is a part of output I got after I used Edirect commands.
![image](https://user-images.githubusercontent.com/47022770/79128795-188f2700-7d72-11ea-8b84-dfabcdddfb70.png)

**Comment by HsiuKangHuang** [comment]
As the result shows, this tax id only has one assembly name. However, you're right. It may be a problem if there are more than one assembly name. 
The other way that letting users add assembly name into the argument themselves may be better.
Maybe I can change the command from 
"RNAseq_annotate.py -i ./example/1049336.tsv -g ./Edan07162013.scaffolds.fa.gz -d" to something like this
"RNAseq_annotate.py -i 1049336.tsv -o [gggsss]_[assemblyname]_RNA-Seq-alignments_[date].bam -g Edan07162013.scaffolds.fa.gz -d"

**Comment by HsiuKangHuang** [comment]
I am thinking that will it be useful for users if I get the assembly name from NCBI and add it into tsv file?
To add assembly name into the argument, if users don't know the name, they can get it or choose the one they want(if there are two or more assemblies) from tsv file.

**Comment by mpoelchau** [comment]
There are actually 2 assemblies in GenBank for that taxid (you can see them if you go to https://www.ncbi.nlm.nih.gov/assembly/?term=ephemera+danica and under 'status - latest' select 'clear'). I don't know how to retrieve all of them using edirect though. Hopefully there's a way.

It would be useful to have information download_sra_metadata.py output the different assembly accessions and their names for a given taxid, so the person running the program could have that information readily available. I'm not sure if that should go in the tsv file - perhaps to stdout?

**Comment by HsiuKangHuang** [comment]
I found that this command "elink -db taxonomy -id 1049336 -target Assembly" will automatically activate filter to get the latest result.
Therefore, even there are two results in taxonomy database, the output of elink can only get the latest one.
The output looked like this.
![image](https://user-images.githubusercontent.com/47022770/79158689-c74c5b00-7da4-11ea-89af-b7b6edd6810d.png)

It seems like only using 'Assembly' as the target will activate the filter. If I use 'Popset' or 'Protein' as the target, the count of the result is corresponding to the amount shown in taxonomy database.

**Comment by HsiuKangHuang** [comment]
Users who want to change the merged file "output.bam" to "[gggsss]_[assembly name]_RNA-Seq-alignments_[yy_mm_dd].bam" can use this command: **RNAseq_annotate.py -i ./example/1049336.tsv -g ./Edan07162013.scaffolds.fa.gz -a Edan_2.0 -d**
I added a new argument "-a" for users to add the organism assembly name for naming output file.
The information of [gggsss] is from the scientific name in tsv file and the information of [assembly name] is from the argument added by user.  

Now, "RNAseq_annotate.py -h" looks like this:

usage: RNAseq_annotate.py [-h] [-i INPUT] [-g GENOME] [-n [NAME]]
                          [-o [OUTDIR]] [-a ASSEMBLY] [-d]Easy to use pipeline built for large-scale RNA-seq mapping with a genome
assemblyoptional arguments:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        A tsv file with a list of SRA runs' information.
  -g GENOME, --genome GENOME
                        A fasta file to align with.
  -n [NAME], --name [NAME]
                        name of the output folder, if not specified, use the
                        time of start
  -o [OUTDIR], --outdir [OUTDIR]
                        directory of output folder at, if not specified, use
                        current folder
  -a ASSEMBLY, --assembly ASSEMBLY
                        The assembly name is used for naming output file.
  -d, --downsample      if specified, a downsampled bam file will be
                        downsampled

**Comment by mpoelchau** [comment]
Looks good!
