### ISSUE TITLE
Add bam file to apollo

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#25]
We'll need to add the final output bam file to apollo.

- Back up existing trackList on apollo server before running. E.g. `cp path_to_trackList.json path_to_trackList-bak.json`
- Make a directory to put the bam, bigwig and index file file on the staging apollo server: `/app/data/[containing directory]/[gggsss]/[assemblyname]/scaffold/analyses/[species]-[genus]-RNA-Seq_[date]_v1.0`.  
- the directory `/app/data/[containing directory]/[gggsss]/jbrowse/data` will need to have a symlink to `/app/data/[containing directory]/[gggsss]/[assemblyname]/scaffold/analyses`. @mpoelchau will probably need to write a one-time script to create the symlinks for all directories, and add this symlink to the organism onboarding workflow. 

Bam file:
- Script to use: https://github.com/GMOD/jbrowse/blob/master/bin/add-bam-track.pl
- Usage: `add_bam_track.pl -i path_to_trackList.json -o path_to_trackList.json --bam_url analyses/[genus]-[species]-RNA-Seq_[date]_v1.0/bamfile --label [gggsss]_[assemblyname]_RNA-Seq-alignments_[date] --category 'RNA-Seq/Mapped Reads' --config '{ "metadata": {SEE BAM_METADATA BELOW} }'`

Bigwig files: 
- Script to use: https://github.com/GMOD/jbrowse/blob/master/bin/add-bw-track.pl
- Usage - downsampled bigwig file: `add_bw_track.pl -i path_to_trackList.json -o path_to_trackList.json --bw_url analyses/[genus]-[species]-RNA-Seq_[date]_v1.0/downsampled-bigwigfile --label [gggsss]_[assemblyname]_RNA-Seq-alignments_[date]_coverage --plot --category 'RNA-Seq/Coverage Plots' --pos_color "#00BFFF" --config '{ "metadata": {SEE BIGWIG_METADATA BELOW} }'`

BAM METADATA:
```
"Analysis provider": "i5k Workspace@NAL",
"Analysis method": "https://github.com/NAL-i5K/NAL_RNA_seq_annotation_pipeline/",
"Data source":"[comma-delimited SRA ACCESSIONS from 'Submission' column in .tsv file]",
"Publication status":"Analysis: NA; Source data: see individual SRA accessions",
 "Track legend":"Dark red alignments: Mapped portion of read aligned to forward strand<br>Light red alignments: Spliced portion of read aligned to forward strand<br>Dark blue alignments: Mapped portion of read aligned to reverse strand<br>Light blue alignments: Spliced portion of read aligned to reverse strand<br>Red marking - deletion in the read relative to the reference<br>Green marking - insertion in the read relative to the reference<br>Yellow marking  - mismatch (hover over the mismatch to see what the snp is)"
```

BIGWIG METADATA (this will likely change in the future, but this is a start):
```
"Analysis provider": "i5k Workspace@NAL",
"Analysis method": "https://github.com/NAL-i5K/NAL_RNA_seq_annotation_pipeline/",
"Data source":"[comma-delimited SRA ACCESSIONS from 'Submission' column in .tsv file]",
"Publication status":"Analysis: NA; Source data: see individual SRA accessions",
"Track legend":"This track represents an X-Y plot of RNA-Seq coverage. The y-axis represents the number of mapped reads. The scale of the y-axis changes with the maximum number of reads aligned in the browser region."
```

**Comment by mpoelchau** [comment]
[containing directory] - yeah, this is confusing. Right now this is either `BCM_i5k_pilot` or `other_species`

**Comment by HsiuKangHuang** [comment]
Is the part "Data source" in metadata still the information of "Submission" column in .tsv file?
Should we use "Run" column instead?

**Comment by mpoelchau** [comment]
Yes, good point - it would be better to use the 'Run' column.
