### ISSUE TITLE
Set up pipeline on Ceres

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#28]
- check to see if the repo and dependencies are already installed in our Ceres project directory 
  - if yes, update them
  - if not, install them
  - see https://scinet.usda.gov/guide/software for instructions on setting up local software on Ceres - since this pipeline should be specific to us we probably don't need to have scinet install it as a module
- test with a large dataset - try all the SRA files from ephemera danica

**Comment by HsiuKangHuang** [comment]
I used following steps to set up env on Ceres:
**1. Setup conda env**
(1) Used conda to create an new env.
(2) Package Entrez-direct and Pysam is not included in the module list of Ceres. Use conda to install them into env. (Python3 and Perl5 may be insatlled into env at the same time)

**2. Git clone RNA_annotation_pipeline and bam_to_bigwig into working directory** 
(1) Git clone branch update-rnannot from this repo.
(2) Git clone branch python3_version from bam_to_bigwig repo (https://github.com/NAL-i5K/bam_to_bigwig.git) and copy bam_to_bigwig.py into rnannot folder.
(3) Use wget to download wigToBigWig (http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig) and add it into PATH.

**3. Load module needed to run this pipline**
(1) Do module load java sratoolkit samtools rsem
(2) Remember to do module unload perl. We need to use the Perl that installed in our env.

**4. Activate conda env**
(1) Do module load minicanda and conda activate env_name

**5. Run setup.py**
(1) Do python3 setup.py install
(If meet "ValueError: bad marshal data", delete .pyc file may solve this problem.) 
find /home/[user_name] -name '*.pyc' -delete

**Comment by mpoelchau** [comment]
After discussion, @HsiuKangHuang will also set up a virtualenv on Ceres for our general use.
