### ISSUE TITLE
sort and index downsampled bam

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#29]
The merged, downsampled bam file needs to be sorted and indexed before it can be used by Apollo. The sorting and indexing should probably happen on local server where the bam file is generated.

- sort command: `samtools sort sample.bam -o sample.sorted.bam`
- index command: `samtools index sample.sorted.bam` . This will generate an index file sample.sorted.bam.bai

**Comment by HsiuKangHuang** [comment]
I let this pipeline generate two bigwig files. One is from original merged bam file and the other one is from merged and downsampled bam file. Both two files are sorted and indexed before converting into bigwig file.

The final output files are:
output.bam / output.sorted.bam / output.sorted.bam.bai / outptut.bigwig
output-downsampled.bam / output-downsampled.sorted.bam / output-downsampled.sorted.bam.bai / output-downsampled.bigwig

Should I change "output" to "[gggsss]_[assemblyname]_RNA-Seq-alignments_[date]" for all of the name of output files?

**Comment by mpoelchau** [comment]
Done.
