### ISSUE TITLE
Figure out how to reduce processing time

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#31]
- Perhaps perform alignment steps (Hisat) in parallel. 
- use different queue

**Comment by HsiuKangHuang** [comment]
Samtools and Hisat are able to run with parallel threads, which can reduce the processing time.
- Hisat
use option "-p"
https://ccb.jhu.edu/software/hisat2/manual.shtml#performance-tuning
- Samtools (both view and sort)
use option "-@"
http://www.htslib.org/doc/1.6/samtools.html

**Comment by mpoelchau** [comment]
The number of threads can be specified in sbatch.sh (https://github.com/NAL-i5K/NAL_RNA_seq_annotation_pipeline/blob/update-rnannot/rnannot/sbatch.sh#L4)
