### ISSUE TITLE
Update trimmomatic and HiSat2 parameters

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#32]
I think we can make the trimmomatic and hisat parameters more stringent than they currently are. 

- Change https://github.com/NAL-i5K/NAL_RNA_seq_annotation_pipeline/blob/master/rnannot/RNAseq_annotate.py#L261 and similar lines to `'LEADING:30', 'TRAILING:30',` 
- For the Hisat alignments, add `--no-mixed` and `--no-discordant` (eg. l. 149, 289, etc)

**Comment by HsiuKangHuang** [comment]
Do I also need to change `'LEADING:3', 'TRAILING:3'` to `'LEADING:30', 'TRAILING:30'` in line 102, 115 and 128?
The option of trimmomatic_jar in these three lines is 'SE', not 'PE'.

**Comment by mpoelchau** [comment]
Yes, please!

**Comment by mpoelchau** [comment]
Thanks @HsiuKangHuang! The mapping looks better with the older parameters (see for example https://apollo-dev.nal.usda.gov/apollo-2.6.0/1250977/jbrowse/index.html?loc=NC_007425.3%3A4199750..4218249&tracks=DNA%2CAnnotations%2Ctricas_current_models%2CTricas_Tcas5.2_RNA-Seq-alignments_2020-05-20_coverage%2CTricas_Tcas5.2_RNA-Seq-alignments_2020-05-31_coverage&highlight=), so let's stick with `LEADING:30', 'TRAILING:30'`
