### ISSUE TITLE
normalize fastq files prior to merging and mapping

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#33]
- try installing bbnorm from the bbmap package. https://sourceforge.net/projects/bbmap/
- guide on how to use bbnorm: https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbnorm-guide/
- example command for paired-end files: `bbnorm.sh in1=read1.fq in2=read2.fq out1=normalized1.fq out2=normalized2.fq target=100`

if this works, then it will probably replace the post-mapping downsampling component.

open questions: 
- what target parameter to use? 
- should we normalize multiple times - first, on individual fastq files, then merge them, then normalize again? 
- how much time and compute does this take with an average set of fastq files?

**Comment by HsiuKangHuang** [comment]
Do "in1=read1.fq" and "in2=read2.fq" mean the output fastq files from the step trimmomatic?
Is this normalizing step before the aligning step?

**Comment by mpoelchau** [comment]
Yes!
