### ISSUE TITLE
Remove intermediate files after processing

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#38]
The RNAseq_annotate.py program downloads a lot of large files, which are not needed after the program has finished (except for debugging purposes). 

Everything should be deleted, except for the final output files; the log files (basically anything ending in .log or .errlog, including in the SRR subdirectories); and source.txt.

It would also be nice if there were a 'debug' argument that would turn the delete behavior off (so, deleting the files would be the default).

**Comment by HsiuKangHuang** [comment]
Okay!
I will also remove .hs2 files and normalized fastq files after the process.
Users can remove option "-t" in sbatch.sh file if they don't want to keep them.

**Comment by HsiuKangHuang** [comment]
Should we remove fastq files of each "run"? For example, the file "SRR9622263_1.fastq" in 2020-06-06-04-35-51/SRR9622263/ directory.

**Comment by mpoelchau** [comment]
Tested, works!
