### ISSUE TITLE
new test files for travis

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#39]
genome file: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz

taxid: 559292

I'd recommend only using run SRR1980743. I'm not sure what the best way is to specify this - create an example .tsv file that travis uses for testing RNAseq_annotate.py, no matter what download_sra_metadata.py downloads?

**Comment by HsiuKangHuang** [comment]
Hi Monica, I download 559292.tsv but I didn't find the run SRR1980743 in tsv file. Therefore, I use SRR1980748 instead.

**Comment by mpoelchau** [comment]
Weird, not sure why it doesn't show up. I picked it because it is small (69.8Mb). SRR1980748 is 1.9Gb - is there a smaller example in your .tsv file?

**Comment by mpoelchau** [comment]
Fixed, new example file in docker container setup, closing.
